<?php  //[STAMP] 538dc7f378f23cf6b6bbfa930c24ec7f
namespace ProtocolTest\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait AppTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
